USE SUCOS_VENDAS

-- CRIANDO BACKUP

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH INIT
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK'
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH COMPRESSION

BACKUP LOG SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS_LOG.BAK' WITH COMPRESSION

 -- RESTAURAÇÃO

RESTORE VERIFYONLY FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS_LOG.BAK'

RESTORE HEADERONLY FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS_LOG.BAK'

USE master
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS

RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS_LOG.BAK' WITH RECOVERY

USE master
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS

RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS_LOG.BAK' WITH FILE = 3, RECOVERY