CREATE DATABASE newDB
	ON PRIMARY(NAME = DB1, FILENAME = 'C:\Git\DB.mdf', SIZE = 8MB, MAXSIZE = 20MB, FILEGROWTH = 10MB),
	(NAME = DB2, FILENAME = 'C:\Git\DB2.ndf', SIZE = 10MB, MAXSIZE = 25MB, FILEGROWTH = 8MB)
	LOG ON (NAME = DBLOG, FILENAME = 'C:\Git\DBLOG.ldf', SIZE = 8MB, MAXSIZE = 20MB, FILEGROWTH = 10MB)

USE newDB

ALTER DATABASE newDB SET RECOVERY SIMPLE
	DBCC SHRINKDATABASE ('newDB', NOTRUNCATE)
	DBCC SHRINKDATABASE ('newDB', TRUNCATEONLY)
ALTER DATABASE newDB SET RECOVERY FULL
