USE SUCOS_VENDAS

CREATE TABLE TST_BACKUP (POS INT)
INSERT INTO TST_BACKUP (POS) VALUES (1)

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH INIT

BACKUP LOG SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH NOINIT

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH DIFFERENTIAL

RESTORE HEADERONLY FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK'

-- RECUPERAÇÃO DOS DADOS (ORDEM: FULL, DIFERENCIAL, LOG)

USE master

ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER  WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS

RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH FILE = 1, NORECOVERY
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH FILE = 3, NORECOVERY
RESTORE LOG SUCOS_VENDAS FROM DISK = 'C:\Git\Academus\SUCOS_VENDAS.BAK' WITH FILE = 2, NORECOVERY
