
SELECT * FROM [VENDEDORES]

BEGIN TRANSACTION

UPDATE [VENDEDORES] SET [COMISSÃO] = [COMISSÃO] * 1.15

SELECT * FROM [VENDEDORES]

INSERT INTO [VENDEDORES] ([Matricula], [NOME], [BAIRRO],[COMISSÃO], [DATA ADMISSÃO], [Ferias])
VALUES ('99999','João da Silva','Icaraí',0.08,'2014-09-01',0)

SELECT * FROM [VENDEDORES]

ROLLBACK

COMMIT

