
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'

INSERT INTO [PRODUTOS] ([Código], [Descrição], [Sabor], [Tamanho], [Embalagem], [Preço])
SELECT [CODIGO DO PRODUTO] AS [Código], [NOME DO PRODUTO] AS [Descrição], [Sabor]
, [Tamanho], [Embalagem], [PREÇO DE LISTA] AS [Preço]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'